### ISSUE TITLE
Add New Contributor 

### ISSUE THREAD

**Issue by egbunse** [StraboSpot/strabo-arcgis-plugin#2]
@jessicagood would you mind adding Kristen Jordan-Koenig (username: KansasGIS) as a contributor to this repository. I looked and apparently to change this I need to have access to the "settings" tab after "graphs" just below the repository name which doesn't exist on my view of the site. If it helps, she's already "watching" the repository.

**Comment by jessicagood** [comment]
I gave you admin rights to this repository and added kansasgis as a contributor. You can control the permissions for read/write access for kansasgis in the Settings menu.

**Comment by egbunse** [comment]
@jessicagood Great! Thank you!
